### ISSUE TITLE
Suggestions for parsing rules of identifiers

### ISSUE THREAD

**Issue by ChangeCaps** [cjavad/dare#9]
For the time being, identifiers/atomic statements, are just a string of connected alphabetic characters, see [char::is_alphabetic](https://doc.rust-lang.org/std/primitive.char.html#method.is_alphabetic).

But we might want to expand this. Here is a list of ideas:
* Allow subscripts. Maybe something like ``A_{0}``.
* Allow superscripts. Maybe something like ``A^{0}``.
* Allow numbers.
* Allow underscores. This would conflict with the proposed suggestion for subscripts above.

**Comment by cjavad** [comment]
Variables / Identifieres will initially be as simple as normal variables in rust and similar langauges. They can consist of alphanumerical characters and underscores. No special support for sub/super script is planned for now.

On a seperate note additional characters such as input to solve an expression via tableau does require the colon character `:` combined with either a TRUE or FALSE identifier to execute that operation so the character `:` is already taken.
